version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/node:16"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker Images
          command: |
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-reverseproxy nguyenvudockeracc/udagram-reverseproxy
            docker tag udagram-api-feed nguyenvudockeracc/udagram-api-feed
            docker tag udagram-api-user nguyenvudockeracc/udagram-api-user
            docker tag udagram-frontend:local nguyenvudockeracc/udagram-frontend
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push nguyenvudockeracc/udagram-reverseproxy
            docker push nguyenvudockeracc/udagram-api-feed
            docker push nguyenvudockeracc/udagram-api-user
            docker push nguyenvudockeracc/udagram-frontend

workflows:
  build:
    jobs:
      - build
