version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: "circleci/node:10.16.0"
    steps:
      - checkout
      - run:
          name: Install `docker-compose`
          command: |
            echo "hello world"
