version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/node:16"
    steps:
      - checkout
      - run:
          name: Always Passing Step
          command: echo "This step always passes"

workflows:
  build:
    jobs:
      - build
