version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/node"

    steps:
      - checkout
      - run:
          name: Always Pass
          command: echo "This job always passes!"

workflows:
  build:
    jobs:
      - build
