version: 2.1

jobs:
  build:
    working_directory: /tmp
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false 

      - run:
          name: Build using `docker-compose`
          command: |
            docker-compose -f $HOME/docker-compose-build.yaml build --parallel
      - run:
          name: Login for Docker Hub
          command: | 
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Tagging
          command: |
            docker tag udagram-reverseproxy nguyenvudockeracc/udagram-reverseproxy
            docker tag udagram-api-feed nguyenvudockeracc/udagram-api-feed
            docker tag udagram-api-user nguyenvudockeracc/udagram-api-user
            docker tag udagram-frontend:local nguyenvudockeracc/udagram-frontend
      - run:
          name: Push to Docker Hub
          command: |
            docker push nguyenvudockeracc/udagram-reverseproxy
            docker push nguyenvudockeracc/udagram-api-feed
            docker push nguyenvudockeracc/udagram-api-user
            docker push nguyenvudockeracc/udagram-frontend

workflows:
  build:
    jobs:
      - build