version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose version

      - run:
          name: Build with Docker Compose
          command: |
            docker-compose -f docker-compose-build.yaml build

workflows:
  version: 2
  build:
    jobs:
      - build
